version: "3.8"
services:

  # PHP service
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-app
#    environment:
#      PHP_IDE_CONFIG: serverName=Docker
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
    ports:
      - "8080:8000"
networks:
  app-network:
    driver: bridge
